GET https://0.0.0.0:3000/hotels HTTP/1.1

###

GET https://0.0.0.0:3000/hotel/62420c8bc13bccb2a324041e HTTP/1.1

###

GET https://0.0.0.0:3000/hotels/Ibis HTTP/1.1

###

POST https://0.0.0.0:3000/hotel HTTP/1.1
Content-Type: application/json

{
    "Name": "Ibis Hotel",
    "City": "Brussel",
    "Address": "Brusselstraat 123",
    "Province": "Brussel",
    "Description": "It's a nice hotel",
    "StarRating": 4.5,
    "Longitude": 1.234567,
    "Latitude": 7.654321,
    "PricePerNightMin": 100,
    "PricePerNightMax": 250.3
}

###

PUT https://0.0.0.0:3000/hotel/62420c8bc13bccb2a324041d HTTP/1.1
Content-Type: application/json

{
    "Name": "Ibis HotelTwo",
    "City": "Brussel",
    "Address": "Brusselstraat 123",
    "Province": "Brussel",
    "Description": "It's a nice hotel",
    "StarRating": 4.5,
    "Longitude": 1.234567,
    "Latitude": 7.654321,
    "PricePerNightMin": 100,
    "PricePerNightMax": 150.3
}

###

DELETE https://0.0.0.0:3000/hotel/62420c8bc13bccb2a324041d HTTP/1.1

###

GET https://0.0.0.0:3000/roomtypes HTTP/1.1

###

GET https://0.0.0.0:3000/roomtype/6243671101783ca48266f16a HTTP/1.1

###

GET https://0.0.0.0:3000/roomtypes/Pr HTTP/1.1

###

POST https://0.0.0.0:3000/roomtype HTTP/1.1
Content-Type: application/json

{
    "Name":"Standard2",
    "NumberOfBeds": 2,
    "SquareMeters": 8,
    "Television": false,
    "Breakfast": true,
    "Airco": false,
    "Wifi": false,
    "View": false
}

###

PUT https://0.0.0.0:3000/roomtype/6243674401783ca48266f16c HTTP/1.1
Content-Type: application/json

{
    "Name":"Standard58",
    "NumberOfBeds": 2,
    "SquareMeters": 8,
    "Television": false,
    "Breakfast": true,
    "Airco": false,
    "Wifi": false,
    "View": false
}

###

DELETE https://0.0.0.0:3000/roomtype/6243674401783ca48266f16c HTTP/1.1

###

GET https://0.0.0.0:3000/reservations HTTP/1.1

###

GET https://0.0.0.0:3000/reservations/Name=Bostoen&FirstName=Toby HTTP/1.1

###

GET https://0.0.0.0:3000/reservation/624439684e6356cf81a5fba3 HTTP/1.1

###

POST https://0.0.0.0:3000/reservation HTTP/1.1
Content-Type: application/json

{
   "Name": "Someone",
   "FirstName": "Random",
   "BirthDate": "2019-07-04T13:33:03.969Z",
   "EMail": "random.someone@student.howest.be",
   "Hotel": {
       "Name": "Ibis Hotel",
        "City": "Brussel",
        "Address": "Brusselstraat 123",
        "Province": "Brussel",
        "Description": "It's a nice hotel",
        "StarRating": 4.5,
        "Longitude": 1.234567,
        "Latitude": 7.654321,
        "PricePerNightMin": 100,
        "PricePerNightMax": 250.3
   },
   "NumberOfRooms": 3,
   "DateOfReservation": "2019-07-04T13:33:03.969Z",
   "TotalPrice": 130.54
}

###

PUT https://0.0.0.0:3000/reservation/6244398a4e6356cf81a5fba4 HTTP/1.1
Content-Type: application/json

{
   "Name": "Johnson",
   "FirstName": "Peter",
   "BirthDate": "2019-07-04T13:33:03.969Z",
   "EMail": "peter.johnson@student.howest.be",
   "Hotel": {
       "Name": "Ibis Hotel",
        "City": "Brussel",
        "Address": "Brusselstraat 123",
        "Province": "Brussel",
        "Description": "It's a nice hotel",
        "StarRating": 4.5,
        "Longitude": 1.234567,
        "Latitude": 7.654321,
        "PricePerNightMin": 100,
        "PricePerNightMax": 250.3
   },
   "NumberOfRooms": 3,
   "DateOfReservation": "2019-07-04T13:33:03.969Z",
   "TotalPrice": 130.54 
}

###

DELETE https://0.0.0.0:3000/reservation/6244398a4e6356cf81a5fba4 HTTP/1.1

###

GET https://0.0.0.0:3000/reviews HTTP/1.1

###

GET https://0.0.0.0:3000/reviews/BostoenToby HTTP/1.1

###

GET https://0.0.0.0:3000/review/62443ea3e728d1969ec7b27d HTTP/1.1

###

POST https://0.0.0.0:3000/review HTTP/1.1
Content-Type: application/json

{
    "Author": "PetersonJohn",
    "StarRating": 3.5,
    "ReviewDescription": "It was a nice stay at the hotel"
}

###

PUT https://0.0.0.0:3000/review/62443ea3e728d1969ec7b27d HTTP/1.1
Content-Type: application/json

{
    "Author": "JohnsonPeter",
    "StarRating": 3.5,
    "ReviewDescription": "It was a nice stay at the hotel"
}

###

DELETE https://0.0.0.0:3000/review/62443ed9e728d1969ec7b27e HTTP/1.1

